name: isru
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pyomo
  - glpk
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - pyyaml
  - jupyter
  - pytest
  - pathlib  # 虽然是标准库，但明确列出

